// apps/website/components/common/experiences/experience-card.tsx
import classNames from 'classnames'
import Link from 'next/link'
import type { Experience } from '@/components/common/experiences/experiences-list'

export default function ExperienceCard({
  brand,
  company,
  website,
  position,
  startYear,
  endYear,
  description,
  projects,
}: Experience) {
  return (
    <div
      className={classNames(
        'w-full rounded-2xl p-6 md:p-8',
        typeof endYear === 'string' ? 'bg-sm-blue/20' : 'bg-neutral-800/60'
      )}
    >
      <div className="flex items-baseline gap-x-1">
        <span className="font-medium">{position}</span>
        <span className="text-sm text-neutral-400">at</span>
        <Link
          href={website}
          target="_blank"
          className="hover:text-sm-blue font-medium underline underline-offset-2 transition-colors"
        >
          {brand}
        </Link>
      </div>
      <span className="text-sm text-neutral-400">
        {company} · {startYear}-{endYear}
      </span>
      <p className="mt-5 text-sm text-neutral-300">{description}</p>
      {!!projects?.length && (
        <div className="mt-5 flex w-fit items-center gap-x-2">
          {projects?.map((project, index) => (
            <span
              key={index}
              className="h-fit rounded-full border border-blue-600 bg-blue-900 px-1.5 text-xs font-medium text-blue-300"
            >
              {project}
            </span>
          ))}
        </div>
      )}
    </div>
  )
}

// apps/resume/components/experience/ExperienceCard.vue
<template>
  <div class="w-full rounded-xl bg-[#f7f7f7] p-6">
    <div
      class="flex w-full flex-col items-start justify-between gap-2 lg:flex-row"
    >
      <div class="w-fit">
        <h3 class="text-lg font-semibold md:text-xl">
          {{ position }} at
          <a
            :href="url"
            target="_blank"
            class="underline-offset-2 hover:underline"
          >
            {{ company }}
          </a>
        </h3>
        <p class="text-sm font-medium md:text-base">
          {{ period }} · {{ location }}
        </p>
      </div>
      <ul class="flex w-fit flex-wrap items-center gap-1 md:gap-x-2">
        <li
          v-for="(skill, key) in skills"
          :key
          class="rounded-md bg-[#dddddd] px-2.5 py-0.5 text-xs font-medium md:text-sm"
        >
          {{ skill }}
        </li>
      </ul>
    </div>
    <ul v-if="!!achievements.length" class="mt-4">
      <li
        v-for="(achievement, key) in achievements"
        :key="key"
        class="flex items-center gap-x-2 text-sm md:text-base"
      >
        <span class="text-[#333333]">•</span>
        <p class="font-medium">{{ achievement }}</p>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
export type ExperienceCardProps = {
  position: string
  company: string
  period: string
  location: string
  achievements: string[]
  skills: string[]
  url: string
}

defineComponent({ name: 'ExperienceCard' })

defineProps<ExperienceCardProps>()
</script>
