// apps/site/components/layout/Footer.vue
<script setup lang="ts">
const currentYear = new Date().getFullYear()
</script>

<template>
  <footer
    class="flex w-full max-w-full flex-col items-start gap-2 px-4 py-8 sm:flex-row sm:items-center sm:justify-between md:mx-auto md:max-w-[600px] md:px-0"
  >
    <p class="text-sm text-gray-300">© {{ currentYear }} Stefano Monolo.</p>
    <p class="text-sm text-gray-300 underline hover:text-white">
      <a
        href="https://git.new/monorepo"
        target="_blank"
        rel="noopener noreferrer"
      >
        Source code on GitHub
      </a>
    </p>
  </footer>
</template>

// apps/website/components/layout/footer.tsx
import Link from 'next/link'

export default function Footer() {
  return (
    <footer className="mx-auto flex w-full max-w-[1000px] flex-col items-center justify-between gap-x-5 gap-y-1 border-t border-neutral-800 px-5 py-4 md:flex-row lg:px-0">
      <span className="text-sm text-neutral-300">
        © {new Date().getFullYear()} Stefano Monolo.
      </span>
      <Link
        href="https://git.new/monorepo"
        target="_blank"
        className="hover:text-sm-white text-sm text-neutral-300 underline underline-offset-2 transition-colors"
      >
        Source code on GitHub
      </Link>
    </footer>
  )
}
