// apps/site/components/layout/Navbar.vue
<script setup lang="ts">
const socials = [
  { name: 'GitHub', icon: 'bi:github', url: 'https://github.com/smonolo' },
  {
    name: 'LinkedIn',
    icon: 'bi:linkedin',
    url: 'https://www.linkedin.com/in/stemon/',
  },
]
</script>

<template>
  <nav>
    <div
      class="flex max-w-full items-center justify-between px-4 py-8 md:mx-auto md:max-w-[600px] md:px-0"
    >
      <NuxtLink
        to="/"
        aria-label="Home"
        class="flex h-11 w-11 items-center justify-center"
      >
        <div class="bg-sm-blue h-7 w-7 rounded" />
      </NuxtLink>
      <div class="flex items-center gap-x-2">
        <a
          v-for="social in socials"
          :key="social.name"
          :href="social.url"
          target="_blank"
          rel="noopener noreferrer"
          :aria-label="social.name"
          class="flex h-11 w-11 items-center justify-center text-gray-500 transition-colors hover:text-white"
        >
          <Icon :name="social.icon" />
        </a>
      </div>
    </div>
  </nav>
</template>

// apps/email-checker/components/Navbar.tsx
import Link from 'next/link'

export default function Navbar() {
  return (
    <header className="bg-sm-black w-full border-b border-neutral-800">
      <div className="mx-auto flex h-14 w-full items-center justify-between gap-x-2 px-4 sm:px-6 md:px-8">
        <Link
          href="/"
          className="flex shrink-0 items-center gap-x-2 transition-opacity hover:opacity-80"
          aria-label="Email Checker Home"
        >
          <div className="bg-sm-blue h-5 w-5 rounded sm:h-6 sm:w-6" />
          <span className="text-xs font-medium text-white sm:text-sm">
            Email Checker
          </span>
        </Link>
      </div>
    </header>
  )
}
